INSERT INTO APP_CREDIT_CHG_LN (USER_ID, CHANGE_TYPE, CHANGE_CATEGORY, CHANGE_CATEGORY_CD, CREDIT_POINT, CHANGE_ON_DTTM, CHANGE_ON_DT_STR)
VALUES(-1, 'ERN', 'SIGN', 'FOR_TEST', 1, 1, '2018-08-01');
INSERT INTO APP_CREDIT_CHG_LN (USER_ID, CHANGE_TYPE, CHANGE_CATEGORY, CHANGE_CATEGORY_CD, CREDIT_POINT, CHANGE_ON_DTTM, CHANGE_ON_DT_STR)
VALUES(-1, 'ERN', 'SIGN', 'FOR_TEST', 2, 2, '2018-08-02');
INSERT INTO APP_CREDIT_CHG_LN (USER_ID, CHANGE_TYPE, CHANGE_CATEGORY, CHANGE_CATEGORY_CD, CREDIT_POINT, CHANGE_ON_DTTM, CHANGE_ON_DT_STR)
VALUES(-1, 'ERN', 'SIGN', 'FOR_TEST', 3, 3, '2018-08-03');
INSERT INTO APP_CREDIT_CHG_LN (USER_ID, CHANGE_TYPE, CHANGE_CATEGORY, CHANGE_CATEGORY_CD, CREDIT_POINT, CHANGE_ON_DTTM, CHANGE_ON_DT_STR)
VALUES(-1, 'ERN', 'SIGN', 'FOR_TEST', 4, 4, '2018-08-04');
INSERT INTO APP_CREDIT_CHG_LN (USER_ID, CHANGE_TYPE, CHANGE_CATEGORY, CHANGE_CATEGORY_CD, CREDIT_POINT, CHANGE_ON_DTTM, CHANGE_ON_DT_STR)
VALUES(-1, 'ERN', 'SIGN', 'FOR_TEST', 5, 5, '2018-08-05');
INSERT INTO APP_CREDIT_CHG_LN (USER_ID, CHANGE_TYPE, CHANGE_CATEGORY, CHANGE_CATEGORY_CD, CREDIT_POINT, CHANGE_ON_DTTM, CHANGE_ON_DT_STR)
VALUES(-1, 'ERN', 'SIGN', 'FOR_TEST', 5, 6, '2018-08-06');


INSERT INTO APP_CREDIT_CHG_LN (USER_ID, CHANGE_TYPE, CHANGE_CATEGORY, CHANGE_CATEGORY_CD, CREDIT_POINT, CHANGE_ON_DTTM, CHANGE_ON_DT_STR)
VALUES(-1, 'ERN', 'SIGN', 'FOR_TEST', 1, 7, '2018-08-11');
INSERT INTO APP_CREDIT_CHG_LN (USER_ID, CHANGE_TYPE, CHANGE_CATEGORY, CHANGE_CATEGORY_CD, CREDIT_POINT, CHANGE_ON_DTTM, CHANGE_ON_DT_STR)
VALUES(-1, 'ERN', 'SIGN', 'FOR_TEST', 2, 8, '2018-08-12');
INSERT INTO APP_CREDIT_CHG_LN (USER_ID, CHANGE_TYPE, CHANGE_CATEGORY, CHANGE_CATEGORY_CD, CREDIT_POINT, CHANGE_ON_DTTM, CHANGE_ON_DT_STR)
VALUES(-1, 'ERN', 'SIGN', 'FOR_TEST', 3, 9, '2018-08-13');

